Update README.md -- Dedalus data generation.
perovai/deepkoopman pull request #34
Opened 2021-07-21 20:29 UTC by sm7610

2021-07-22 08:07 UTC, jaggbow requested changes

2021-07-22 08:07 UTC, jaggbow commented on README.md
> +These are generated using `aiphysim/dedalus-dataset/rayeigh-benard.py`, which is derived from the [MeshfreeFlowNet code (Jiang et al. 2020)](https://github.com/maxjiang93/space_time_pde).
For the data generation I didn't use MeshfreeFlowNet's code

2021-07-22 12:36 UTC, jaggbow approved these changes

2021-07-23 12:36 UTC, vict0rsch approved these changes

2021-07-23 12:36 UTC, merged